---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: vplugindemo
spec:
  destination:
    namespace: vplugindemo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/hinunbi/openshift-gitops-vault-plugin.git'
    targetRevision: HEAD
    path: 3-application
  syncPolicy:
    automated:
      prune: true
